Repository Verisec/frejaeidclient, pull requests merged in 2020-01, with the labels that each got.

#3 Added configuration for release
  FrejaEidClient/pom.xml
Labels: enhancement

#4 Updated version.
  FrejaEidClient/pom.xml
Labels: good first issue

#5 Updated README.MD
  README.md
Labels: documentation
